### ISSUE TITLE
Auto injection as bower component

### ISSUE THREAD

**Issue by alefr** [radu-cigmaian/ng-xCharts#8]
We're using a swiips gulp-yeoman generator for a project where we have ng-xCharts as a dependency.
Currently there is no main part in the bower.json specifying which files to auto inject only leaving *ng-xCharts.js* to be auto injected.

A fix is as easy as to add i.e:
```
"main": [
  "xcharts.js"
  "ng-xCharts.js",
  "xcharts.css "
],
```
to the bower.json.

Ofc I can create a pull request for this if needed but wasn't sure this is how you intended it so decided to post it as an issue first.

**Comment by radu-cigmaian** [comment]
Done, sorry for the late response
